name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      
    - name: make ipa
      run: make
    - uses: actions/upload-artifact@v3
      with:
       name: IPA Download
       path: pissra1n.ipa
    - name: make tipa
      run: make && mv pissra1n.ipa pissra1n.tipa
    - uses: actions/upload-artifact@v3
      with:
       name: tIPA Download (TrollStore)
       path: pissra1n.tipa
