name: Makefile CI

on:
  push:
    branches: [ "ios17-support" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      
    - name: Make IPA
      run: make
    - uses: actions/upload-artifact@v3
      with:
       name: IPA Download
       path: cumra1n.ipa
    - name: Make tIPA (for TrollStore)
      run: make && mv pissra1n.ipa pissra1n.tipa
    - uses: actions/upload-artifact@v3
      with:
       name: tIPA Download (TrollStore)
       path: cumra1n.tipa
